export const navigationGroups = [
  {
    id: "inicio",
    label: "Início",
    eyebrow: "Cockpit",
    description:
      "Painel geral da operação, agenda e recursos de crescimento do ERP.",
    items: [
      "Índice",
      "Dashboard",
      "Agenda",
      "Minha conta",
      "Integrações",
      "Upgrade de plano",
      "Sobre a versão",
      "Ajuda do ERP",
      "Ferramentas",
      "Loja de extensões",
    ],
  },
  {
    id: "cadastros",
    label: "Cadastros",
    eyebrow: "Base",
    description:
      "Entidades mestras para clientes, catálogo, campanhas, serviços e operação comercial.",
    items: [
      "Clientes e Fornecedores",
      "Produtos",
      "Campanhas Promocionais",
      "Serviços",
      "Categorias dos Produtos",
      "Vendedores",
      "Embalagens",
      "Relatórios",
    ],
  },
  {
    id: "suprimentos",
    label: "Suprimentos",
    eyebrow: "Supply",
    description:
      "Estoques, compras e rotinas de entrada para dar previsibilidade ao abastecimento.",
    items: [
      "Controle de Estoques",
      "Ordens de Compra",
      "Serviços Tomados",
      "Notas de Entrada",
      "Conferência de compra",
      "Necessidades de Compra",
      "Giro de Estoque",
      "FCI",
      "Relatórios",
    ],
  },
  {
    id: "vendas",
    label: "Vendas",
    eyebrow: "Revenue",
    description:
      "CRM, pedidos, notas, automações e execução ponta a ponta da esteira comercial.",
    items: [
      "CRM",
      "Painel de Automações",
      "PDV",
      "Propostas Comerciais",
      "Pedidos de Venda",
      "Notas Fiscais",
      "Comissões",
      "Notas Fiscais Consumidor",
      "Performance de Vendas",
      "Margem Contribuição",
      "Custos do e-commerce",
      "Separação",
      "Expedição",
      "Devoluções de venda",
      "Relatórios",
    ],
  },
  {
    id: "financas",
    label: "Finanças",
    eyebrow: "Cashflow",
    description: "Caixa, contas, conciliação e leitura financeira consolidada.",
    items: [
      "Caixa",
      "Conta Digital",
      "pix grátis",
      "Contas a Pagar",
      "Contas a Receber",
      "Cobranças Bancárias",
      "Extratos Bancários",
      "Relatórios",
    ],
  },
  {
    id: "servicos",
    label: "Serviços",
    eyebrow: "Service",
    description:
      "Gestão de contratos, ordens de serviço, notas e cobrança operacional.",
    items: [
      "Contratos",
      "Ordens de Serviço",
      "Notas de Serviço",
      "Cobranças",
      "Relatórios",
    ],
  },
] as const;

export const supportLinks = [
  "Configurações",
  "Canal de ideias",
  "Suporte",
  "Envios DaBi Tech",
  "Ecommerce",
] as const;

export type NavigationGroupId = (typeof navigationGroups)[number]["id"];

export const menuRoutes = {
  "Clientes e Fornecedores": "/clientes-e-fornecedores",
  Produtos: "/produtos",
  "Campanhas Promocionais": "/campanhas-promocionais",
  "Categorias dos Produtos": "/categorias-dos-produtos",
  Embalagens: "/embalagens",
  Relatórios: "/relatorios",
  Vendedores: "/vendedores",
  Serviços: "/servicos",
  "Controle de Estoques": "/controle-de-estoques",
  Índice: "/indice",
  Dashboard: "/dashboard",
  Agenda: "/agenda",
  "Minha conta": "/minha-conta",
  "Dados da empresa": "/dados-da-empresa",
  Integrações: "/integracoes",
  "Upgrade de plano": "/upgrade-plano",
  "Sobre a versão": "/sobre-versao",
  Ferramentas: "/ferramentas",
  "Loja de extensões": "/loja-de-extensoes",
} as const;

export const menuItemByPath: Record<string, keyof typeof menuRoutes> = {
  "/clientes-e-fornecedores": "Clientes e Fornecedores",
  "/produtos": "Produtos",
  "/campanhas-promocionais": "Campanhas Promocionais",
  "/categorias-dos-produtos": "Categorias dos Produtos",
  "/embalagens": "Embalagens",
  "/relatorios": "Relatórios",
  "/vendedores": "Vendedores",
  "/servicos": "Serviços",
  "/controle-de-estoques": "Controle de Estoques",
  "/indice": "Índice",
  "/dashboard": "Dashboard",
  "/agenda": "Agenda",
  "/minha-conta": "Minha conta",
  "/dados-da-empresa": "Dados da empresa",
  "/integracoes": "Integrações",
  "/upgrade-plano": "Upgrade de plano",
  "/sobre-versao": "Sobre a versão",
  "/ferramentas": "Ferramentas",
  "/loja-de-extensoes": "Loja de extensões",
  "/": "Índice",
};
